Repository Sea-Bottle/Sea-Bottle-Jackal, pull requests merged in 2022-03, with the labels that each got.

#4 Add linter
  .github/workflows/super-linter.yml
Labels: enhancement

#3 Add liquid rescaling algorithm
  src/backend/seam_carve.py
Labels: enhancement

#7 Add docstrings to seam_carve module
  src/backend/seam_carve.py
Labels: documentation

#6 Add another linter
  .github/workflows/pylint.yml
Labels: enhancement

#12 Fix linter issues
  .github/workflows/pylint.yml
Labels: bug

#10 Style tests
  .github/workflows/pylint.yml
  .github/workflows/super-linter.yml
  .github/workflows/tests.yml
  README.md
  requirements.txt
  src/backend/seam_carve.py
  tests/test_style.py
Labels: enhancement

#11 Add a wrapper to get videos directly from an image
  src/backend/jackalify.py
Labels: enhancement

#14 Fix incorrect handling of command line arguments
  src/backend/jackalify.py
Labels: bug

#15 Fix docstrings
  src/backend/jackalify.py
Labels: documentation
